// Code generated by "stringer -type=RuleId -linecomment"; DO NOT EDIT.

package analyzer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[applyDefaultSelectLimitId-0]
	_ = x[validateOffsetAndLimitId-1]
	_ = x[validateStarExpressionsId-2]
	_ = x[ValidateCreateTableId-3]
	_ = x[validateAlterTableId-4]
	_ = x[validateExprSemId-5]
	_ = x[loadStoredProceduresId-6]
	_ = x[validateDropTablesId-7]
	_ = x[resolveDropConstraintId-8]
	_ = x[validateDropConstraintId-9]
	_ = x[resolveCreateSelectId-10]
	_ = x[resolveSubqueriesId-11]
	_ = x[resolveUnionsId-12]
	_ = x[ValidateColumnDefaultsId-13]
	_ = x[validateCreateTriggerId-14]
	_ = x[validateReadOnlyDatabaseId-15]
	_ = x[validateReadOnlyTransactionId-16]
	_ = x[validateDatabaseSetId-17]
	_ = x[validatePrivilegesId-18]
	_ = x[validateGroupById-19]
	_ = x[flattenTableAliasesId-20]
	_ = x[pushdownSubqueryAliasFiltersId-21]
	_ = x[replaceSubqueriesId-22]
	_ = x[validateCheckConstraintId-23]
	_ = x[replaceCountStarId-24]
	_ = x[replaceCrossJoinsId-25]
	_ = x[moveJoinCondsToFilterId-26]
	_ = x[simplifyFiltersId-27]
	_ = x[pushNotFiltersId-28]
	_ = x[hoistOutOfScopeFiltersId-29]
	_ = x[unnestInSubqueriesId-30]
	_ = x[unnestExistsSubqueriesId-31]
	_ = x[finalizeSubqueriesId-32]
	_ = x[finalizeUnionsId-33]
	_ = x[loadTriggersId-34]
	_ = x[processTruncateId-35]
	_ = x[ResolveAlterColumnId-36]
	_ = x[stripTableNameInDefaultsId-37]
	_ = x[optimizeJoinsId-38]
	_ = x[pushFiltersId-39]
	_ = x[applyIndexesFromOuterScopeId-40]
	_ = x[pruneTablesId-41]
	_ = x[assignExecIndexesId-42]
	_ = x[inlineSubqueryAliasRefsId-43]
	_ = x[eraseProjectionId-44]
	_ = x[flattenDistinctId-45]
	_ = x[replaceAggId-46]
	_ = x[pushdownAggregationsId-47]
	_ = x[replaceIdxSortId-48]
	_ = x[insertTopNId-49]
	_ = x[replaceIdxOrderByDistanceId-50]
	_ = x[applyHashInId-51]
	_ = x[resolveInsertRowsId-52]
	_ = x[applyTriggersId-53]
	_ = x[applyProceduresId-54]
	_ = x[assignRoutinesId-55]
	_ = x[modifyUpdateExprsForJoinId-56]
	_ = x[applyForeignKeysId-57]
	_ = x[interpreterId-58]
	_ = x[validateResolvedId-59]
	_ = x[validateOrderById-60]
	_ = x[validateSchemaSourceId-61]
	_ = x[validateIndexCreationId-62]
	_ = x[ValidateOperandsId-63]
	_ = x[validateIntervalUsageId-64]
	_ = x[validateSubqueryColumnsId-65]
	_ = x[validateUnionSchemasMatchId-66]
	_ = x[validateAggregationsId-67]
	_ = x[validateDeleteFromId-68]
	_ = x[cacheSubqueryAliasesInJoinsId-69]
	_ = x[QuoteDefaultColumnValueNamesId-70]
	_ = x[TrackProcessId-71]
	_ = x[engineOverridesId-72]
}

const _RuleId_name = "applyDefaultSelectLimitvalidateOffsetAndLimitvalidateStarExpressionsvalidateCreateTablevalidateAlterTablevalidateExprSemloadStoredProceduresvalidateDropTablesresolveDropConstraintvalidateDropConstraintresolveCreateSelectresolveSubqueriesresolveUnionsvalidateColumnDefaultsvalidateCreateTriggervalidateReadOnlyDatabasevalidateReadOnlyTransactionvalidateDatabaseSetvalidatePrivilegesvalidateGroupByflattenTableAliasespushdownSubqueryAliasFiltersreplaceSubqueriesvalidateCheckConstraintsreplaceCountStarreplaceCrossJoinsmoveJoinConditionsToFiltersimplifyFilterspushNotFiltershoistOutOfScopeFiltersunnestInSubqueriesunnestExistsSubqueriesfinalizeSubqueriesfinalizeUnionsloadTriggersprocessTruncateResolveAlterColumnstripTableNamesFromColumnDefaultsoptimizeJoinspushFiltersapplyIndexesFromOuterScopepruneTablesassignExecIndexesinlineSubqueryAliasRefseraseProjectionflattenDistinctreplaceAggpushdownAggregationsreplaceIdxSortinsertTopNNodesreplaceIdxOrderByDistanceapplyHashInresolveInsertRowsapplyTriggersapplyProceduresassignRoutinesmodifyUpdateExprsForJoinapplyForeignKeysinterpretervalidateResolvedvalidateOrderByvalidateSchemaSourcevalidateIndexCreationvalidateOperandsvalidateIntervalUsagevalidateSubqueryColumnsvalidateUnionSchemasMatchvalidateAggregationsvalidateDeleteFromcacheSubqueryAliasesInJoinsquoteDefaultColumnValueNamestrackProcessengineOverrides"

var _RuleId_index = [...]uint16{0, 23, 45, 68, 87, 105, 120, 140, 158, 179, 201, 220, 237, 250, 272, 293, 317, 344, 363, 381, 396, 415, 443, 460, 484, 500, 517, 543, 558, 572, 594, 612, 634, 652, 666, 678, 693, 711, 744, 757, 768, 794, 805, 822, 845, 860, 875, 885, 905, 919, 934, 959, 970, 987, 1000, 1015, 1029, 1053, 1069, 1080, 1096, 1111, 1131, 1152, 1168, 1189, 1212, 1237, 1257, 1275, 1302, 1330, 1342, 1357}

func (i RuleId) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RuleId_index)-1 {
		return "RuleId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuleId_name[_RuleId_index[idx]:_RuleId_index[idx+1]]
}
